export interface BibleBook {
  id: number;
  name: string;
  abbrev: string;
  chapters: number;
  testament: 'VT' | 'NT';
}

export const BIBLE_BOOKS: BibleBook[] = [
  { id: 1, name: "Gênesis", abbrev: "gn", chapters: 50, testament: "VT" },
  { id: 2, name: "Êxodo", abbrev: "ex", chapters: 40, testament: "VT" },
  { id: 3, name: "Levítico", abbrev: "lv", chapters: 27, testament: "VT" },
  { id: 4, name: "Números", abbrev: "nm", chapters: 36, testament: "VT" },
  { id: 5, name: "Deuteronômio", abbrev: "dt", chapters: 34, testament: "VT" },
  { id: 6, name: "Josué", abbrev: "js", chapters: 24, testament: "VT" },
  { id: 7, name: "Juízes", abbrev: "jz", chapters: 21, testament: "VT" },
  { id: 8, name: "Rute", abbrev: "rt", chapters: 4, testament: "VT" },
  { id: 9, name: "1 Samuel", abbrev: "1sm", chapters: 31, testament: "VT" },
  { id: 10, name: "2 Samuel", abbrev: "2sm", chapters: 24, testament: "VT" },
  { id: 11, name: "1 Reis", abbrev: "1rs", chapters: 22, testament: "VT" },
  { id: 12, name: "2 Reis", abbrev: "2rs", chapters: 25, testament: "VT" },
  { id: 13, name: "1 Crônicas", abbrev: "1cr", chapters: 29, testament: "VT" },
  { id: 14, name: "2 Crônicas", abbrev: "2cr", chapters: 36, testament: "VT" },
  { id: 15, name: "Esdras", abbrev: "ez", chapters: 10, testament: "VT" },
  { id: 16, name: "Neemias", abbrev: "ne", chapters: 13, testament: "VT" },
  { id: 17, name: "Ester", abbrev: "et", chapters: 10, testament: "VT" },
  { id: 18, name: "Jó", abbrev: "jó", chapters: 42, testament: "VT" },
  { id: 19, name: "Salmos", abbrev: "sl", chapters: 150, testament: "VT" },
  { id: 20, name: "Provérbios", abbrev: "pv", chapters: 31, testament: "VT" },
  { id: 21, name: "Eclesiastes", abbrev: "ec", chapters: 12, testament: "VT" },
  { id: 22, name: "Cantares", abbrev: "ct", chapters: 8, testament: "VT" },
  { id: 23, name: "Isaías", abbrev: "is", chapters: 66, testament: "VT" },
  { id: 24, name: "Jeremias", abbrev: "jr", chapters: 52, testament: "VT" },
  { id: 25, name: "Lamentações", abbrev: "lm", chapters: 5, testament: "VT" },
  { id: 26, name: "Ezequiel", abbrev: "ez", chapters: 48, testament: "VT" },
  { id: 27, name: "Daniel", abbrev: "dn", chapters: 12, testament: "VT" },
  { id: 28, name: "Oséias", abbrev: "os", chapters: 14, testament: "VT" },
  { id: 29, name: "Joel", abbrev: "jl", chapters: 3, testament: "VT" },
  { id: 30, name: "Amós", abbrev: "am", chapters: 9, testament: "VT" },
  { id: 31, name: "Obadias", abbrev: "ob", chapters: 1, testament: "VT" },
  { id: 32, name: "Jonas", abbrev: "jn", chapters: 4, testament: "VT" },
  { id: 33, name: "Miquéias", abbrev: "mq", chapters: 7, testament: "VT" },
  { id: 34, name: "Naum", abbrev: "na", chapters: 3, testament: "VT" },
  { id: 35, name: "Habacuque", abbrev: "hc", chapters: 3, testament: "VT" },
  { id: 36, name: "Sofonias", abbrev: "sf", chapters: 3, testament: "VT" },
  { id: 37, name: "Ageu", abbrev: "ag", chapters: 2, testament: "VT" },
  { id: 38, name: "Zacarias", abbrev: "zc", chapters: 14, testament: "VT" },
  { id: 39, name: "Malaquias", abbrev: "ml", chapters: 4, testament: "VT" },
  { id: 40, name: "Mateus", abbrev: "mt", chapters: 28, testament: "NT" },
  { id: 41, name: "Marcos", abbrev: "mc", chapters: 16, testament: "NT" },
  { id: 42, name: "Lucas", abbrev: "lc", chapters: 24, testament: "NT" },
  { id: 43, name: "João", abbrev: "jo", chapters: 21, testament: "NT" },
  { id: 44, name: "Atos", abbrev: "atos", chapters: 28, testament: "NT" },
  { id: 45, name: "Romanos", abbrev: "rm", chapters: 16, testament: "NT" },
  { id: 46, name: "1 Coríntios", abbrev: "1co", chapters: 16, testament: "NT" },
  { id: 47, name: "2 Coríntios", abbrev: "2co", chapters: 13, testament: "NT" },
  { id: 48, name: "Gálatas", abbrev: "gl", chapters: 6, testament: "NT" },
  { id: 49, name: "Efésios", abbrev: "ef", chapters: 6, testament: "NT" },
  { id: 50, name: "Filipenses", abbrev: "fp", chapters: 4, testament: "NT" },
  { id: 51, name: "Colossenses", abbrev: "cl", chapters: 4, testament: "NT" },
  { id: 52, name: "1 Tessalonicenses", abbrev: "1ts", chapters: 5, testament: "NT" },
  { id: 53, name: "2 Tessalonicenses", abbrev: "2ts", chapters: 3, testament: "NT" },
  { id: 54, name: "1 Timóteo", abbrev: "1tm", chapters: 6, testament: "NT" },
  { id: 55, name: "2 Timóteo", abbrev: "2tm", chapters: 4, testament: "NT" },
  { id: 56, name: "Tito", abbrev: "tt", chapters: 3, testament: "NT" },
  { id: 57, name: "Filemom", abbrev: "fm", chapters: 1, testament: "NT" },
  { id: 58, name: "Hebreus", abbrev: "hb", chapters: 13, testament: "NT" },
  { id: 59, name: "Tiago", abbrev: "tg", chapters: 5, testament: "NT" },
  { id: 60, name: "1 Pedro", abbrev: "1pe", chapters: 5, testament: "NT" },
  { id: 61, name: "2 Pedro", abbrev: "2pe", chapters: 3, testament: "NT" },
  { id: 62, name: "1 João", abbrev: "1jo", chapters: 5, testament: "NT" },
  { id: 63, name: "2 João", abbrev: "2jo", chapters: 1, testament: "NT" },
  { id: 64, name: "3 João", abbrev: "3jo", chapters: 1, testament: "NT" },
  { id: 65, name: "Judas", abbrev: "jd", chapters: 1, testament: "NT" },
  { id: 66, name: "Apocalipse", abbrev: "ap", chapters: 22, testament: "NT" },
];
